#!/bin/sh

# Copyright (c) 2017 Aaron Bieber <aaron@bolddaemon.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

#config file
CONFIG="${XDG_CONFIG_HOME:-~/.config}/sctd/sctdrc"

# defaults
# these values of sumand and increment work for making the screen temperature
# at noon (12:00) be 6500k, the default screen temperature on x11
SUMAND=5060
INCREMENT=2
UPDATE=60

# load config if it exists
[ -f "$CONFIG" ] && . "$CONFIG"

# use the right sct executable
SCT=$(command -v sct)
[ -z "$SCT" ] && SCT=$(command -v xsct)

if [ ! -e "$SCT" ]; then
    echo "Please install sct!"
    exit 1;
fi

# set HM var to current time of the day in minutes
setHM () {
    H=$(date +"%H" | sed -e 's/^0//')
    M=$(date +"%M" | sed -e 's/^0//')
    HM=$((H*60 + M))
}

if [ "$#" -gt 0 ]; then
    case "$1" in
        debug) DBGOUT=1;;
    esac
fi

while true; do
    setHM

    if [ $HM -gt 720 ]; then
        SUM=$(( SUMAND + INCREMENT * (1440 - HM) ))
    else
        SUM=$(( SUMAND + INCREMENT * HM ))
    fi

    [ "$DBGOUT" = 1 ] && echo $HM
    [ "$DBGOUT" = 1 ] && echo $SUM
    $SCT $SUM

    sleep $UPDATE
done
