#!/bin/sh

# Copyright (c) 2017 Aaron Bieber <aaron@bolddaemon.com>
# Copryright (c) 2017 Inokentiy Babushkin <twk@twki.de>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

#config file
CONFIG="${XDG_CONFIG_HOME:-~/.config}/sctd/sctdrc"

# defaults
# default value of max temp is same as the default screen color temp of x11
TEMP_MIN=4500
TEMP_MAX=6500
INTERVAL=60

# load config if it exists
[ -f "$CONFIG" ] && . "$CONFIG"

# use the right sct executable
SCT=$(command -v sct)
[ -z "$SCT" ] && SCT=$(command -v xsct)

if [ ! -e "$SCT" ]; then
    echo "Please install sct!"
    exit 1;
fi

# calculate increment
INCREMENT=$(( (TEMP_MAX - TEMP_MIN) / 720 ))
# 12 hours is 720 minutes

# set HM var to current time of the day in minutes
setHM () {
    H=$(date +"%H" | sed -e 's/^0//')
    M=$(date +"%M" | sed -e 's/^0//')
    HM=$((H*60 + M))
}

setTEMP() {
    if [ $HM -gt 720 ]; then
        TEMP=$(( TEMP_MIN + INCREMENT * (1440 - HM) ))
    else
        TEMP=$(( TEMP_MIN + INCREMENT * HM ))
    fi
}

tick() {
    setHM
    setTEMP
    [ "$DBGOUT" = 1 ] && echo $HM
    [ "$DBGOUT" = 1 ] && echo $TEMP
    $SCT $TEMP
}

if [ "$#" -gt 0 ]; then
    case "$1" in
        debug)   DBGOUT=1  ;;
        oneshot) ONESHOT=1 ;;
    esac
fi

if [ "$ONESHOT" -eq 1 ]; then
    tick
else
    while true; do
        tick
        sleep "$INTERVAL"
    done
fi
